<FirstCoffe>
    id: fk_box 
    size_hint: None, None
    size: 400, 700
    pos_hint: {"center_x": 0.5, "center_y": 0.5}
    elevation: 25
    padding: 25
    spacing: 25
    radius: 20
    orientation: 'vertical'
    line_color: (0.2, 0.2, 0.2, 0.8)

    MDLabel:
        id: welcome_label
        text: "LOG IN"
        font_size: 30
        halign: 'center'
        size_hint_y: None
        height: self.texture_size[1]
        padding_y: 6