# Menu item in the DrawerList list.


<ItemDrawer>
    theme_text_color: "red"
    on_release: self.parent.set_color_item(self)

    IconLeftWidget:
        id: icon
        icon: root.icon
        theme_text_color: "Custom"
        text_color: root.text_color

MDScreen:
    md_bg_color: app.theme_cls.primary_light
    FitImage:
        id: coffee
        size_hint: (1, 1)
        # size: (root.width, root.height)
        source: "image/bean_bg.jpg"
    
    MDNavigationLayout:

        ScreenManager:

            MDScreen:

                MDToolbar:
                    title: "Navigation Drawer"
                    elevation: 10
                    pos_hint: {"top": 1}
                    md_bg_color: app.theme_cls.primary_color
                    specific_text_color: "#000000"
                    left_action_items:
                        [['menu', lambda x: nav_drawer.set_state("open")]]
                    right_action_items: 
                        [["dots-vertical", lambda x: app.callback()], ["clock", lambda x: app.callback_2()]]
                    elevation:5
                
                MDToolbar:
                    title: "Navigation Drawer"
                    elevation: 10
                    pos_hint: {"bottom": 1}
                    md_bg_color: app.theme_cls.primary_color
                    specific_text_color: "#000000"

                    right_action_items:
                        [
                        ["home", lambda x: app.callback(x), "Home"],
                        ["coffee", lambda x: app.callback(x), "Coffee order"],
                        ["coffee-maker", lambda x: app.callback(x), "Make Coffe"],
                        ["account-cancel", lambda x: app.callback(x), "Account"],
                        ]
                    
                    


        MDNavigationDrawer:
            id: nav_drawer
            md_bg_color: app.theme_cls.primary_color
            radius: (0, 16, 16, 0) if self.anchor == "left" else (16, 0, 0, 16)

            ContentNavigationDrawer:
                orientation: 'vertical'
                padding: "8dp"
                spacing: "8dp"
            
                MDLabel:
                    text: "Attreya"
                    font_style: "Subtitle1"
                    size_hint_y: None
                    height: self.texture_size[1]
                MDLabel:
                    text: "attreya01@gmail.com"
                    size_hint_y: None
                    font_style: "Caption"
                    height: self.texture_size[1]
                ScrollView:
                    DrawerList:
                        id: md_list
                        
                        MDList:
                            OneLineIconListItem:
                                text: "Profile"
                                IconLeftWidget:
                                    icon: "face-profile"
      
                            OneLineIconListItem:
                                text: "Upload"
                                IconLeftWidget:
                                    icon: "upload"
                                    
                           
                            OneLineIconListItem:
                                text: "Logout"
                                IconLeftWidget:
                                    icon: "logout"
                